### ISSUE TITLE
Broken link on External DOM Mutations page

### ISSUE THREAD

**Issue by robdodson** [developit/preact-www#109]
Just noticed the datepicker webpackbin demo on this page (https://github.com/developit/preact-www/blob/master/content/guide/external-dom-mutations.md) seems to be invalid now. Maybe they changed their URL structure?

**Comment by developit** [comment]
Totally - I hadn't noticed that. Looks like they also broke JSX support, but I found a workaround and updated the URL. Thanks for catching :)
