### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by wildlyinaccurate** [developit/preact-www#131]
I often find myself going to the React docs when I forget an API. Would you be opposed to a PR that adds an "API" page with a list of function signatures and short description of each?

**Comment by oren** [comment]
This would be fantastic

**Comment by developit** [comment]
+1 for this, even I would find that useful.

Maybe we can start with this?

[![](https://pbs.twimg.com/media/DAhBsSPXgAMTJh2.jpg)](https://twitter.com/_developit/status/867015201383731200/photo/1)

**Comment by wildlyinaccurate** [comment]
Great, I'll try and make a start later this week! I'll definitely start with that, and I also wanted to document `render()` because I _always_ trip up on what to put in the second and third args to make it replace a server-rendered node.

**Comment by oren** [comment]
yes! the render function can drive me nuts. I'll buy you a beer if we ever meet.
