### ISSUE TITLE
ProductHunt link

### ISSUE THREAD

**Issue by mstijak** [developit/preact-www#151]
Just want to report a minor issue. I clicked "Get It" on [Product Hunt's Preact page](https://www.producthunt.com/posts/preact) and got redirected to 
https://preactjs.com/?ref=producthunt, which renders a blank page. I guess it's due to the unknown query string parameter `ref`.

**Comment by developit** [comment]
Oh my goodness that's a hilarious bug - the `ref` query parameter gets parsed by `preact-router`, which passes it down as a prop to the current route.  The thing is - `ref` is a special property and can only be a function, so it's bailing out.  Router really needs to omit `key` and `ref` from the props it's willing to pass down!

**Comment by developit** [comment]
Fixed in https://github.com/developit/preact-router/commit/18fadf0fd874cbb3e38a87f2fcf9273f2152082c

**Comment by developit** [comment]
Fixed!
