### ISSUE TITLE
I made a library maybe insteresting.

### ISSUE THREAD

**Issue by xialvjun** [developit/preact-www#16]
[xialvjun/preact-flyd](https://github.com/xialvjun/preact-flyd), a preact version of [theadam/react-flyd](https://github.com/theadam/react-flyd)

**Comment by developit** [comment]
Interesting indeed!  Do you want to submit a PR to add it here, or should I?
The page is here: https://github.com/developit/preact-www/blob/master/content/about/libraries-addons.md

**Comment by developit** [comment]
[You're famous!](https://preactjs.com/about/libraries-addons#integrations)

<img width="765" src="https://cloud.githubusercontent.com/assets/105127/16883157/9a1fb168-4a90-11e6-9588-42f3eda736d9.png">

**Comment by xialvjun** [comment]
haha, thanks
