### ISSUE TITLE
[Question] Blog content from Markdown

### ISSUE THREAD

**Issue by talvasconcelos** [developit/preact-www#170]
Hi guys, i'm trying to build a blog with preact and would like to use the method used for preactjs.com to "fetch" content from markdown files on the /content folder.

I'd also like to have the blog post in github. that way i could add a new blog post without having to build the website everytime and would give the chance to users to make pull request to add or change info.

1. Can i have just the posts on a git repositorie and get them on the fly when user visits the blog?
2. Do i need to host the all build on gh-pages to be able to do this?
3. How do i "fetch" the count of files in the content folder, or get the frontmatter for meta tags?

I've been lurking at the preact-www code and it's all there i guess, i just need to understand it better

Thanks,
Tiago

**Comment by developit** [comment]
Hi @talvasconcelos - you could definitely reuse the technique from preact-www for your use-case.  
The main thing you'd have to change to fetch content from Github would be to change the URL generated here:
https://github.com/developit/preact-www/blob/master/src/components/content-region.js#L40-L41

... to hit your repo (perhaps through rawgit):

```js
	let path = 'https://rawgit.com/talvasconcelos/blog/master/content',
		url = `${path}/${name.replace(/^\//,'')}`,
```
