### ISSUE TITLE
Add list of sites using Preact in production

### ISSUE THREAD

**Issue by developit** [developit/preact-www#18]
As per this [suggestion on Twitter](https://twitter.com/MongiaChirag/status/755381283245559808), we should compile a list of sites/apps using Preact.  Feel free to comment here so we can get a decent list going prior to adding it to the website.

Here's a few I'm aware of to start things off!
- [preactjs.com](https://preactjs.com) (of course!)
- [GuriVR](https://gurivr.com) - VR builder by the great @impronunciable
- [Algolia Instantsearch.js](https://community.algolia.com/instantsearch.js/) is using Preact in production
- [ESBench](https://esbench.com) - replacement for the late JSPerf
- [Nectarine.rocks](https://nectarine.rocks) - unofficial peach.cool web/android app
- [Synacor](http://synacor.com) is using Preact in a number of projects (more on that soon)
- [Tictail.com](http://tictail.com) is using preact for it's authentication interface (c/o @eldh)
- [Lagom](http://tofuness.github.io/Lagom) - interactive video gallery by @tofuness 
- [GregJS](https://gregjs.com) - @greg-js's blog, built with Hexo + Preact

I know there are lots more, so I'll go ping people!

**Comment by impronunciable** [comment]
@developit https://github.com/coralproject/elkhorn it's under development but it uses preact for the embeddable widgets. I'll let you know when we get this working on newsrooms (hopefully we will have large newsrooms using it)

**Comment by developit** [comment]
@impronunciable looks super interesting! (and over my head haha)

**Comment by tofuness** [comment]
I built this video gallery :frog: :+1:  https://github.com/tofuness/Lagom

**Comment by developit** [comment]
@tofuness the effects on this are super cool, I hadn't viewed it on desktop until now 😍

**Comment by eldh** [comment]
Tictail.com is using preact for it's auth interface.
