### ISSUE TITLE
Overconfidence in Preact.createElement documentation

### ISSUE THREAD

**Issue by natevw** [developit/preact-www#187]
The documentation for `Preact.h()`/`Preact.createElement()` is incorrect. It says:

> All remaining arguments are collected into a children Array, and be any of the following:
> 
> * Scalar values
> * More Virtual DOM elements
> * Infinitely nested Arrays of the above

So according to the documentation I should be able to pass an infinitely nested array of virtual DOM elements. Well actually, this hangs the browser:

```
let children = [h('span')]
children.push(children)
preact.render(h('div', {}, children), document.body)
```

:trollface:

**Comment by developit** [comment]
That's not infinitely nested, that's circular ;)

**Comment by natevw** [comment]
Somewhat curiously, I didn't get a maximum stack size exception even after waiting a while!

Obviously this is contrived, but couldn't resist… (feel free to close, with or without prejudice :-)

**Comment by developit** [comment]
lol I might close for now, but I'm pondering if there's a better word to use here.
