### ISSUE TITLE
Browser support page confusing

### ISSUE THREAD

**Issue by LukeLindsey** [developit/preact-www#214]
[This page](https://preactjs.com/about/browser-support) is misleading as a reader. The text mentions supporting Safari, Edge, and IE9+, but the browser matrix SVG that is shown doesn't seem to indicate that.

**Comment by developit** [comment]
It's a live chart, and we're experiencing issues with the IE tests.

**Comment by LukeLindsey** [comment]
Looks like the test issues are all worked out. Can't thank you enough for this library :smiley:
