### ISSUE TITLE
reset scroll after routing

### ISSUE THREAD

**Issue by robbiewxyz** [developit/preact-www#22]
I'm in the progress of trying out Preact for the first time, and I ran into a little quirk on your website:  if I scroll halfway down the homepage and then head to another page using the top nav bar or a link, that page will load pre-scrolled part of the way down.

Anyway, certainly not any disaster, but it's a little annoying to have to scroll back up before I start reading.

... you know, maybe I'll use this as my first Preact task and send you a PR if I can handle the framework.

**Comment by developit** [comment]
That would be a great PR for sure!  I had noticed that effect too, I think there is just a little complexity in resetting scroll only for forward navigation and not backward. Cheers!

**Comment by robbiewxyz** [comment]
Hmm, yea...  I see a commented-out attempt at that in [app.js:20](https://github.com/developit/preact-www/blob/master/src/components/app.js#L20).

Maybe this will need an addition to preact-router, adding some kind of functionality similar to `pushState`'s "state object" first parameter?  You might add a `onBeforeNavigate` event in which you could save a bit of state information that could be used later (i.e. back button) to fix the scroll.  This [SO post](http://stackoverflow.com/a/16732655/2619939) shows a jQuery implementation...

It looks like I've probably bitten off more than I can chew for a my first Preact work.  :smile:  But I'll keep fiddling around.

**Comment by developit** [comment]
That could work, yup.  Another option would be to hook link clicks and reset the scroll, since links are the only way of navigating forwards.  Thinking maybe something similar to this:

```js
document.body.addEventListener('click', e => {
  let t = e.target;
  do {
    // navigation within the site always uses /absolute/paths
    if (t.nodeName==='A' && (t.getAttribute('href') || '')[0]==='/' && !t.hash && !t.target) {
      setTimeout(scrollToTop, 1);
      // we can let the normal link action through, scroll fix is now applied
    }
  } while ((t=t.parentNode));
});

function scrollToTop() {
  document.body.scrollTop = 0;
}
```

This could also be written as a VNode hook (maybe a bit overcomplicated for this), or just good ol' DOM as above.

I actually really like the idea of some basic hooks in `preact-router`, too.  Also, I believe `<Router />` could be modified to pass on the "source" of navigation to its existing `onRoute()` event, which might make the implementation this simple:

```js
handleRoute = ({ source }) => {
  if (source==='link') {
    document.body.scrollTop = 0;
  }
};
render() {
  return (
    <Router onRoute={this.handleRoute}>
    // ...etc
```

---

Most people don't even try to go this deep until they are debugging in production, haha.

**Comment by robbiewxyz** [comment]
The advantage of an `onBeforeNavigate` approach would be:

1. You scroll halfway down the first page
2. You click a link to navigate to the second page
3. The page stores your scroll location
4. The second page loads, scrolling is reset to the top
3. You hit the back button
3. The page stores your scroll location
4. The first page loads back, restoring the scroll state you left it at
5. You hit the forward button
6. The second page loads, restoring it's scroll state

That approach gets a bit tricky... what do you think?

**Comment by robbiewxyz** [comment]
Here's a JSFiddle I threw together to demo how to save and restore page state with the history API:

[jsfiddle.net/robbiewxyz/6f48u0de](https://jsfiddle.net/robbiewxyz/6f48u0de/)

Type a little something, navigate to one of the links, type another bit, and then use the forward and back buttons.  The text persists and is restored with each page in your history.  In our case, instead of editing text, the scroll location would be saved when navigating and restored with the history.

**Comment by developit** [comment]
I'm wondering how this would work for subregion scrolling - maybe it's fine to just do it for the page?
