### ISSUE TITLE
save my poor battery

### ISSUE THREAD

**Issue by robbiewxyz** [developit/preact-www#23]
I love animated logos; it looks terrific on the homepage!  Could we maybe limit the animation in the title bar on docs pages to just moving on hover or something?  I've been sitting here studying, trying to pick up Preact, when my laptop fan starts humming.  I'm on battery, so that's kind of frustrating...

I'm on a newer laptop, quad-core i3, so I'm sure this is even worse on some of the low-power chromebooks or something.

What do y'all think?

**Comment by developit** [comment]
Ah, that's true. The animation isn't done via CSS, so it's not GPU-accelerated or nicely composited (it was a demo animation.

Maybe something as simple as having it pause after a few seconds and just spin once every minute or so?

**Comment by robbiewxyz** [comment]
Wow.  I just realized how that animation demonstrates Preact's ability to do virtual DOM and 60fps.  Pretty cool.  I'm working on a pull request...

**Comment by developit** [comment]
Yup :)

Looking forward to the PR 👍

**Comment by developit** [comment]
Fixed via your #27 💃
