### ISSUE TITLE
preactjs.com glitches on hover

### ISSUE THREAD

**Issue by developit** [developit/preact-www#24]
_(Migrated from developit/preact@247)_

@coiel said:

> something wrong with CSS in Stable Google Chrome (no time for look deeper)

**Comment by developit** [comment]
@coiel - did you mean when hovering over menus? What operating system are you seeing the issue on?

**Comment by coiel** [comment]
Core i7. Archlinux up to date, Gnome, Google Chrome stable. 
Yes. Visible full-page rerendering on  menu item focus. i.e. it's working but looks very bad.

**Comment by developit** [comment]
Hmm - do you see a similar artifact on other 3D CSS transforms?  Here's a few examples:

https://webkit.org/blog-files/3d-transforms/transform-style.html
http://www.cssscript.com/demo/pure-css-dropdown-menu-with-3d-flipping-animation/
http://www.cssplay.co.uk/menus/cssplay-3d-flip-menu-ie10.html

**Comment by developit** [comment]
I deployed a fix for this, seemed to work for me.  I started seeing the issue on a lower resolution monitor so I was able to debug it :)
