### ISSUE TITLE
Update docs around props.children

### ISSUE THREAD

**Issue by dwelle** [developit/preact-www#277]
The statement that `props.children` is always an array is no longer true since Preact X.

In particular:

- https://preactjs.com/about/project-goals#non-goals

    > Children, since Preact always boxes children as an Array
    
- https://preactjs.com/guide/differences-to-react#whats-missing

    > [Children](https://facebook.github.io/react/docs/top-level-api.html#reactchildren): Not necessary in Preact, because `props.children` is *always an Array*.

Would open PR but not sure about what to change it to.

**Comment by hassanbazzi** [comment]
We're doing an entire update to the docs in the next few days. :)

**Comment by dwelle** [comment]
Nvm then :)
