### ISSUE TITLE
"Getting Started" link contrast

### ISSUE THREAD

**Issue by montogeek** [developit/preact-www#30]
Hi!

I noticed that is hard to see the "Getting started" link in the homepage, I have checked it with Contrast radio tools as http://webaim.org/resources/contrastchecker/ giving me the next result:
![screen shot 2016-08-26 at 12 13 33](https://cloud.githubusercontent.com/assets/1002461/18014045/bee9a212-6b86-11e6-8ed8-d612b4516197.png)

As you can see it is really hard to see.

If we change the color to white the contrast radio improved:
![screen shot 2016-08-26 at 12 14 41](https://cloud.githubusercontent.com/assets/1002461/18014099/0987ac7e-6b87-11e6-9e83-0c83da9b6bfc.png), passing the [Web Content Accessibility Guidelines](https://www.w3.org/WAI/intro/wcag)

It would look like this in the actual website:

**Normal state**:
![screen shot 2016-08-26 at 12 09 38](https://cloud.githubusercontent.com/assets/1002461/18014137/2fdef6ca-6b87-11e6-953e-c949d92112dd.png)

**Hover state**:
![screen shot 2016-08-26 at 12 09 48](https://cloud.githubusercontent.com/assets/1002461/18014159/44e80b88-6b87-11e6-8886-40143272b7b0.png)

Would you accept a PR implementing this?

Thanks!

**Comment by developit** [comment]
Sure! Great find 💃
