### ISSUE TITLE
Extending Component page has problems rendering first code block

### ISSUE THREAD

**Issue by KrofDrakula** [developit/preact-www#33]
Case in point:

![image](https://cloud.githubusercontent.com/assets/112161/19513014/5dc9dbac-95e6-11e6-810b-1cc4c4b332d5.png)

Specifically, the doubly-nested square bracket seems to be breaking parsing and doesn't output the full HTML. The source Markdown file contains the correct code.

I've tried the latest `marked` parsing in https://runkit.com/npm/marked and it seems to work just fine with the code block, but I didn't have enough time to determine if `highlight-js` is the culprit. Or it might be some other processing module in the chain that causes that line to break.

**Comment by developit** [comment]
Hmm, yeah that's a bit funky.  Likely just need to update marked as you mentioned.
