### ISSUE TITLE
Improve link navigation

### ISSUE THREAD

**Issue by cesarandreu** [developit/preact-www#50]
This is a very minor nit, but preact's docs navigate when you press cmd+click on macos. Normally the desired behavior is to open the link in a new tab without navigating away. It's a minor thing, but it's the those little things that make all the difference sometimes!

react-router's [Link](https://github.com/ReactTraining/react-router/blob/v4/modules/Link.js) component gets this right, so I figured I'd share as a point of reference:

```js
const isLeftClickEvent = (event) =>
  event.button === 0

const isModifiedEvent = (event) =>
  !!(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey)

// ...

    if (
      !event.defaultPrevented && // onClick prevented default
      !this.props.target && // let browser handle "target=_blank" etc.
      !isModifiedEvent(event) &&
      isLeftClickEvent(event)
    ) {
      event.preventDefault()
      this.handleTransition()
    }
```

**Comment by developit** [comment]
Hi @cesarandreu - I think this can actually be fixed by updating [preact-router](https://github.com/developit/preact-router), since more recent versions actually just hook into HTML links.
