### ISSUE TITLE
Problem with font rendering on website

### ISSUE THREAD

**Issue by petehouston** [developit/preact-www#57]
There is a problem displaying text on the dropdown menu.

![preactjs-website-render](https://cloud.githubusercontent.com/assets/9006720/20513861/4fe489ac-b0bb-11e6-8554-623d2611d2a8.png)

Environment:

* Windows 10
* Browser: Google Chrome

**Comment by developit** [comment]
Hmm, interesting. There's a fix in the case that makes them not blurry on OSX, maybe it has the opposite effect under windows? It was only with certain screens.

**Comment by petehouston** [comment]
On OSX, when I hover over drop-down list menu item, it is quite slow on hovering effect, not immediately. Do you feel the same thing?

**Comment by developit** [comment]
Hmm, no it just looks like a normal :hover for me. Maybe it's a GPU thing? There's a 3D transform on the menu itself.

**Comment by dmitrykurmanov** [comment]
I think it is because of ` transform: ... perspective(1000px);` in https://github.com/developit/preact-www/blob/8d216b99a860871625a778cb6fa668fe76e8ee27/src/components/header/style.less.

**Comment by developit** [comment]
Ah true, we can probably just have it transition to no perspective.

**Comment by developit** [comment]
Fix is live :)
