### ISSUE TITLE
SVGs are not cached on https://preactjs.com/

### ISSUE THREAD

**Issue by abhishekisnot** [developit/preact-www#58]
I assume https://preactjs.com/ is PWA which should work even in offline mode. But the SVG images served on preactjs.com are marked explictly with no-cache pragma. This causes the SVG images to not-render on page reload in offline mode (note: all other parts work correctly).

![screen shot 2016-11-22 at 10 57 53 pm](https://cloud.githubusercontent.com/assets/802242/20553255/d6c9b518-b107-11e6-90b0-4eaf6a72eb1c.png)

![screen shot 2016-11-22 at 11 04 06 pm](https://cloud.githubusercontent.com/assets/802242/20553270/0859e47c-b108-11e6-9420-9654b2172c0b.png)

Is this on purpose? If not, what solution do you propose?

**Comment by developit** [comment]
Ah, no that's something surge.sh adds. I think the URLs need to be whitelisted for caching via OfflinePlugin /cc @nekr

**Comment by NekR** [comment]
Hey @developit! How exactly you move `assets/` from `src/` to `dist/`? I doesn't seem to be done with `file-loader`. i.e. `offline-plugin` doesn't see them in webpack's output assets.

**Comment by NekR** [comment]
@developit oh, I see you just copy it in here: https://github.com/developit/preact-www/blob/master/package.json#L10
If you do it outside of webpack then you will need to add each file manually to the list of `offline-plugin` caches. The easier way though it to just use `webpack-copy-plugin` which will do copy for you and populate webpack's output assets so `offline-plugin` could use it.

**Comment by developit** [comment]
Ahh amazing I will definitely be switching to that.

**Comment by developit** [comment]
@NekR would switching to `webpack-copy-plugin` mean I could place the external images into `additional` or `optional` sections via a `*` wildcard?

**Comment by NekR** [comment]
@developit  Yeah, absolutely! 

Btw, what's this option? https://github.com/developit/preact-www/blob/master/webpack.config.babel.js#L156

There is no such option. There is `responseType: 'network-first'` in v4 though :-)

**Comment by NekR** [comment]
I can make a PR to migrate to v4 btw :-)

**Comment by developit** [comment]
Oh, I guess that's why it was serving from cache first! Would love a V4 PR btw.
