### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by fjorgemota** [developit/preact-www#68]
Hello!

I was searching for new UI libraries and found PreactJS..

But, while doing a research about the library, I found a few broken links in the section about performance, in the text: "It even includes extra performance features like [customizable update batching](https://preactjs.com/guide/configuration#debounceRendering), optional [async rendering](https://preactjs.com/guide/configuration#syncComponentUpdates), DOM recycling and optimized event handling via Linked State.".

So..as this seems the repository that stores the code for the site - and as I not found any other references to this problem in other issues - , I am just leaving this issue here to reference for now.

Thanks and keep the good work. :)

**Comment by developit** [comment]
Ah, yes this came up a few days ago and I forgot to file an issue. We'll use this to track it :)
Likely just a new "Options" page in under Guide, or maybe full-on API Documentation, since it's all annotated via JSDoc anyway.

**Comment by vitormalencar** [comment]
hey guys, I think we can close this since the previous commit was merge in the master solving this problem.
