### ISSUE TITLE
Document the matched version of React

### ISSUE THREAD

**Issue by rattrayalex** [developit/preact-www#8]
Since Preact strives to be mostly-compatible with React (which is a top feature – thanks!!), it would be terrific if the "differences to react" page documented the versions that the page is applicable to.

**Comment by developit** [comment]
I've added a section about React version compatibility with some high level information about how things are assessed and decided.  Let me know if there's anything else you think should be added!

**Comment by rattrayalex** [comment]
Thanks, that's definitely helpful! 

I was hoping for a number on the site, so I know how "current" the docs are – let's say React releases v16 tomorrow with new API features, well, I want to see "as of React v15" on the preact website so I know that preact might not yet have those v16 features. 

Thoughts?

**Comment by developit** [comment]
Yeah that makes sense. I had avoided putting a number, but it would be helpful to see that the documentation was written against a given version as being "current".  I'll update it shortly :)

**Comment by rattrayalex** [comment]
😄
