### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by developit** [developit/preact-www#96]
/cc @pluma @bmatzner who expressed an interest :)

#### Process:

- Copy everything except `lang` from `content/` into `content/lang/de/`
- Translate the markdown files
- Add "de" to the [list of languages](https://github.com/developit/preact-www/blob/master/src/config.json#L7)

**Comment by bmatzner** [comment]
translation is in progress. hold your breath.

**Comment by maxrugen** [comment]
@bmatzner Need any help?
