### ISSUE TITLE
Translate to French

### ISSUE THREAD

**Issue by developit** [developit/preact-www#97]
/cc @xtuc

#### Process:

- Copy everything except `lang` from `content/` into `content/lang/fr/`
- Translate the markdown files
- Add "fr" to the [list of languages](https://github.com/developit/preact-www/blob/master/src/config.json#L7)

**Comment by efflam** [comment]
I'll help with that when I can free some time

**Comment by mlcdf** [comment]
I can help too. :)

**Comment by xtuc** [comment]
Cool, thanks for the help. Are you on Preact's Slack?

**Comment by efflam** [comment]
@xtuc yes

**Comment by mlcdf** [comment]
I am now (@mlcdf too).

**Comment by warpdesign** [comment]
I'm in too!
